[book]
authors = ["CloudStreet"]
language = "en"
src = "src"
title = "Reinforcement Learning with Q"
description = "Sutton & Barto's Reinforcement Learning: An Introduction, implemented in kdb+/q"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
mathjax-support = true
git-repository-url = "https://github.com/cloudstreet-dev/Reinforcement-Learning-with-Q"
edit-url-template = "https://github.com/cloudstreet-dev/Reinforcement-Learning-with-Q/edit/main/{path}"
additional-css = ["custom.css"]

[output.html.fold]
enable = false
